# Generated by Django 5.1.7 on 2025-03-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=255)),
                ('Postnom', models.CharField(max_length=255, null=True)),
                ('Prénom', models.CharField(max_length=55, null=True)),
                ('Sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('Niveau_Etudes', models.CharField(choices=[('Diplômé Etat', 'D6'), ('Gradué', 'GD'), ('Licencié', 'L'), ('Autre', 'A')], max_length=200)),
                ('Date_de_naissance', models.DateField()),
            ],
        ),
    ]
