# Generated by Django 5.1.7 on 2025-03-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Enseignants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='Niveau_Etudes',
            field=models.CharField(choices=[('D6', 'Diplômé Etat'), ('GD', 'Gradué'), ('L', 'Licencié'), ('A', 'Autre')], max_length=200),
        ),
    ]
