# Generated by Django 5.1.7 on 2025-04-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Enseignants', '0002_alter_enseignant_niveau_etudes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='Niveau_Etudes',
            field=models.CharField(choices=[('Diplômé Etat', 'Diplômé Etat'), ('Gradué', 'Gradué'), ('Licencié', 'Licencié'), ('Autre', 'Autre')], max_length=200),
        ),
    ]
