# Generated by Django 5.1.7 on 2025-03-29 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gestion_Enseignants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libellé', models.CharField(max_length=255)),
                ('Titulaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Enseignants.enseignant')),
            ],
        ),
    ]
