# Generated by Django 5.1.7 on 2025-03-29 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gestion_Années_Scolaires', '0001_initial'),
        ('Gestion_Classes', '0001_initial'),
        ('Gestion_Elèves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Année', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Années_Scolaires.année_scolaire')),
                ('Classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Classes.classe')),
                ('Elève', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Elèves.elève')),
            ],
        ),
    ]
